services:
  app:
    build: .
    container_name: factory_transport_app
    ports:
      - "8000:8000"
    volumes:
      # - ./app:/app/app  Windowsの app フォルダだけをコンテナの /app/app に同期
      - .:/app # Windowsでプロジェクト全体をコンテナの /app に同期
    env_file:
      - .env
    depends_on:
      - db
    # app/main.py の中にある app 変数を起動するためのコマンド
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  db:
    image: mysql:8.0
    container_name: factory_transport_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - "23306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: